CREATE TABLE IF NOT EXISTS user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  nickname VARCHAR(50) NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'STUDENT',
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- 正式项目 password 应使用 bcrypt 哈希存储，当前基础版使用明文密码演示。

CREATE TABLE IF NOT EXISTS workspace (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(255) DEFAULT NULL,
  root_path VARCHAR(255) NOT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS kg_node (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  category VARCHAR(100) NOT NULL,
  difficulty INT NOT NULL DEFAULT 1,
  description TEXT,
  content TEXT,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS kg_relation (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  source_id BIGINT NOT NULL,
  target_id BIGINT NOT NULL,
  relation_type VARCHAR(50) NOT NULL,
  description TEXT,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_kg_relation_source FOREIGN KEY (source_id) REFERENCES kg_node (id) ON DELETE CASCADE,
  CONSTRAINT fk_kg_relation_target FOREIGN KEY (target_id) REFERENCES kg_node (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS learning_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  node_id BIGINT NOT NULL,
  progress_status VARCHAR(30) NOT NULL DEFAULT 'NOT_STARTED',
  note TEXT,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_learning_record_user FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE,
  CONSTRAINT fk_learning_record_node FOREIGN KEY (node_id) REFERENCES kg_node (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_character (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  workspace_id BIGINT DEFAULT NULL,
  name VARCHAR(100) NOT NULL,
  role_prompt TEXT NOT NULL,
  avatar VARCHAR(255) DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_character_workspace FOREIGN KEY (workspace_id) REFERENCES workspace (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_chat_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  lesson_id BIGINT NULL,
  lesson_session_id BIGINT NULL,
  node_id BIGINT NULL,
  action_type VARCHAR(50) NOT NULL,
  role VARCHAR(30) NOT NULL,
  speaker VARCHAR(50) NULL,
  user_message TEXT NULL,
  ai_response TEXT NULL,
  prompt_snapshot MEDIUMTEXT NULL,
  model_name VARCHAR(100) NULL,
  success TINYINT NOT NULL DEFAULT 1,
  fallback_used TINYINT NOT NULL DEFAULT 0,
  latency_ms INT NULL,
  error_message TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS admin_stat_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  log_type VARCHAR(50) NOT NULL,
  stat_date DATE NOT NULL,
  stat_value INT NOT NULL DEFAULT 0,
  remark VARCHAR(255) DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ========== V0.4 新增 ==========

CREATE TABLE IF NOT EXISTS textbook (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(100) NOT NULL,
  course_name VARCHAR(100) NOT NULL,
  total_pages INT NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'not_prepared',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lesson (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  textbook_id BIGINT NOT NULL,
  lesson_order INT NOT NULL,
  title VARCHAR(100) NOT NULL,
  objective TEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'locked',
  textbook_pages VARCHAR(50) NULL,
  max_duration_minutes INT NOT NULL DEFAULT 40,
  estimated_duration_minutes INT NULL,
  summary TEXT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_lesson_textbook FOREIGN KEY (textbook_id) REFERENCES textbook (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lesson_script (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  lesson_id BIGINT NOT NULL,
  script_order INT NOT NULL,
  role VARCHAR(30) NOT NULL,
  speaker VARCHAR(50) NOT NULL,
  content TEXT NOT NULL,
  message_type VARCHAR(50) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_lesson_script_lesson FOREIGN KEY (lesson_id) REFERENCES lesson (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lesson_node_mapping (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  lesson_id BIGINT NOT NULL,
  node_id BIGINT NOT NULL,
  role VARCHAR(30) NOT NULL,
  display_order INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_lnm_lesson FOREIGN KEY (lesson_id) REFERENCES lesson (id) ON DELETE CASCADE,
  CONSTRAINT fk_lnm_node FOREIGN KEY (node_id) REFERENCES kg_node (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS graph_progress (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  node_id BIGINT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'locked',
  completed_lesson_id BIGINT NULL,
  completed_at TIMESTAMP NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_gp_node FOREIGN KEY (node_id) REFERENCES kg_node (id) ON DELETE CASCADE,
  CONSTRAINT fk_gp_lesson FOREIGN KEY (completed_lesson_id) REFERENCES lesson (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lesson_session (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  lesson_id BIGINT NOT NULL,
  started_at TIMESTAMP NULL,
  ended_at TIMESTAMP NULL,
  duration_seconds INT NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'in_progress',
  end_type VARCHAR(30) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ls_lesson FOREIGN KEY (lesson_id) REFERENCES lesson (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ========== V0.7 新增 ==========

CREATE TABLE IF NOT EXISTS preparation_task (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  textbook_id BIGINT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'pending',
  current_step VARCHAR(100) NULL,
  source_file VARCHAR(255) NOT NULL,
  model_name VARCHAR(100) NULL,
  error_message TEXT NULL,
  started_at TIMESTAMP NULL,
  finished_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS preparation_artifact (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  task_id BIGINT NOT NULL,
  artifact_type VARCHAR(50) NOT NULL,
  content_json MEDIUMTEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pa_task FOREIGN KEY (task_id) REFERENCES preparation_task (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
